# This rule is not used by the project kube-greencosts itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants create/delete/get/list/patch/update/watch permissions over greencosts.hstr.nl.
# This role is intended for users authorized to manage ClusterHibernatePolicy objects.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-greencosts
    app.kubernetes.io/managed-by: kustomize
  name: clusterhibernatepolicy-editor-role
rules:
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - clusterhibernatepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - clusterhibernatepolicies/status
  verbs:
  - get
