# This rule is not used by the project kube-greencosts itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to greencosts.hstr.nl resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-greencosts
    app.kubernetes.io/managed-by: kustomize
  name: energypricesource-viewer-role
rules:
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - energypricesources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - energypricesources/status
  verbs:
  - get
