---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - energyawarecronjobs
  - energypricesources
  - hibernatepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - energyawarecronjobs/finalizers
  - energypricesources/finalizers
  - hibernatepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - greencosts.hstr.nl
  resources:
  - energyawarecronjobs/status
  - energypricesources/status
  - hibernatepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - list
  - watch
