//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityWindow) DeepCopyInto(out *AvailabilityWindow) {
	*out = *in
	if in.Weekdays != nil {
		in, out := &in.Weekdays, &out.Weekdays
		*out = make([]Weekday, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityWindow.
func (in *AvailabilityWindow) DeepCopy() *AvailabilityWindow {
	if in == nil {
		return nil
	}
	out := new(AvailabilityWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHibernatePolicy) DeepCopyInto(out *ClusterHibernatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHibernatePolicy.
func (in *ClusterHibernatePolicy) DeepCopy() *ClusterHibernatePolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterHibernatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHibernatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHibernatePolicyList) DeepCopyInto(out *ClusterHibernatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterHibernatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHibernatePolicyList.
func (in *ClusterHibernatePolicyList) DeepCopy() *ClusterHibernatePolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterHibernatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHibernatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHibernatePolicySpec) DeepCopyInto(out *ClusterHibernatePolicySpec) {
	*out = *in
	if in.AvailabilityWindows != nil {
		in, out := &in.AvailabilityWindows, &out.AvailabilityWindows
		*out = make([]AvailabilityWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Action.DeepCopyInto(&out.Action)
	if in.IncludedResources != nil {
		in, out := &in.IncludedResources, &out.IncludedResources
		*out = make([]WorkloadType, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedResources != nil {
		in, out := &in.ExcludedResources, &out.ExcludedResources
		*out = make([]WorkloadType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHibernatePolicySpec.
func (in *ClusterHibernatePolicySpec) DeepCopy() *ClusterHibernatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterHibernatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHibernatePolicyStatus) DeepCopyInto(out *ClusterHibernatePolicyStatus) {
	*out = *in
	if in.HibernatedWorkloads != nil {
		in, out := &in.HibernatedWorkloads, &out.HibernatedWorkloads
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHibernatePolicyStatus.
func (in *ClusterHibernatePolicyStatus) DeepCopy() *ClusterHibernatePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterHibernatePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProviderConfig) DeepCopyInto(out *CustomProviderConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProviderConfig.
func (in *CustomProviderConfig) DeepCopy() *CustomProviderConfig {
	if in == nil {
		return nil
	}
	out := new(CustomProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyAwareCronJob) DeepCopyInto(out *EnergyAwareCronJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyAwareCronJob.
func (in *EnergyAwareCronJob) DeepCopy() *EnergyAwareCronJob {
	if in == nil {
		return nil
	}
	out := new(EnergyAwareCronJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnergyAwareCronJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyAwareCronJobList) DeepCopyInto(out *EnergyAwareCronJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnergyAwareCronJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyAwareCronJobList.
func (in *EnergyAwareCronJobList) DeepCopy() *EnergyAwareCronJobList {
	if in == nil {
		return nil
	}
	out := new(EnergyAwareCronJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnergyAwareCronJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyAwareCronJobSpec) DeepCopyInto(out *EnergyAwareCronJobSpec) {
	*out = *in
	out.EnergyPriceSource = in.EnergyPriceSource
	out.EnergyStrategy = in.EnergyStrategy
	in.CronJob.DeepCopyInto(&out.CronJob)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyAwareCronJobSpec.
func (in *EnergyAwareCronJobSpec) DeepCopy() *EnergyAwareCronJobSpec {
	if in == nil {
		return nil
	}
	out := new(EnergyAwareCronJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyAwareCronJobStatus) DeepCopyInto(out *EnergyAwareCronJobStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]corev1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextCronWindow != nil {
		in, out := &in.NextCronWindow, &out.NextCronWindow
		*out = (*in).DeepCopy()
	}
	if in.NextScheduledTime != nil {
		in, out := &in.NextScheduledTime, &out.NextScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyAwareCronJobStatus.
func (in *EnergyAwareCronJobStatus) DeepCopy() *EnergyAwareCronJobStatus {
	if in == nil {
		return nil
	}
	out := new(EnergyAwareCronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyPriceSource) DeepCopyInto(out *EnergyPriceSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyPriceSource.
func (in *EnergyPriceSource) DeepCopy() *EnergyPriceSource {
	if in == nil {
		return nil
	}
	out := new(EnergyPriceSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnergyPriceSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyPriceSourceList) DeepCopyInto(out *EnergyPriceSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnergyPriceSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyPriceSourceList.
func (in *EnergyPriceSourceList) DeepCopy() *EnergyPriceSourceList {
	if in == nil {
		return nil
	}
	out := new(EnergyPriceSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnergyPriceSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyPriceSourceSpec) DeepCopyInto(out *EnergyPriceSourceSpec) {
	*out = *in
	out.CacheTTL = in.CacheTTL
	in.Providers.DeepCopyInto(&out.Providers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyPriceSourceSpec.
func (in *EnergyPriceSourceSpec) DeepCopy() *EnergyPriceSourceSpec {
	if in == nil {
		return nil
	}
	out := new(EnergyPriceSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyPriceSourceStatus) DeepCopyInto(out *EnergyPriceSourceStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Prices != nil {
		in, out := &in.Prices, &out.Prices
		*out = make([]PricePoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyPriceSourceStatus.
func (in *EnergyPriceSourceStatus) DeepCopy() *EnergyPriceSourceStatus {
	if in == nil {
		return nil
	}
	out := new(EnergyPriceSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnergyStrategySpec) DeepCopyInto(out *EnergyStrategySpec) {
	*out = *in
	out.EstimatedDuration = in.EstimatedDuration
	out.ScheduleWindow = in.ScheduleWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnergyStrategySpec.
func (in *EnergyStrategySpec) DeepCopy() *EnergyStrategySpec {
	if in == nil {
		return nil
	}
	out := new(EnergyStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EneverConfig) DeepCopyInto(out *EneverConfig) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EneverConfig.
func (in *EneverConfig) DeepCopy() *EneverConfig {
	if in == nil {
		return nil
	}
	out := new(EneverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntsoeConfig) DeepCopyInto(out *EntsoeConfig) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntsoeConfig.
func (in *EntsoeConfig) DeepCopy() *EntsoeConfig {
	if in == nil {
		return nil
	}
	out := new(EntsoeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernateAction) DeepCopyInto(out *HibernateAction) {
	*out = *in
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernateAction.
func (in *HibernateAction) DeepCopy() *HibernateAction {
	if in == nil {
		return nil
	}
	out := new(HibernateAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernatePolicy) DeepCopyInto(out *HibernatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernatePolicy.
func (in *HibernatePolicy) DeepCopy() *HibernatePolicy {
	if in == nil {
		return nil
	}
	out := new(HibernatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HibernatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernatePolicyList) DeepCopyInto(out *HibernatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HibernatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernatePolicyList.
func (in *HibernatePolicyList) DeepCopy() *HibernatePolicyList {
	if in == nil {
		return nil
	}
	out := new(HibernatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HibernatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernatePolicySpec) DeepCopyInto(out *HibernatePolicySpec) {
	*out = *in
	if in.WorkloadTypes != nil {
		in, out := &in.WorkloadTypes, &out.WorkloadTypes
		*out = make([]WorkloadType, len(*in))
		copy(*out, *in)
	}
	if in.AvailabilityWindows != nil {
		in, out := &in.AvailabilityWindows, &out.AvailabilityWindows
		*out = make([]AvailabilityWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Action.DeepCopyInto(&out.Action)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernatePolicySpec.
func (in *HibernatePolicySpec) DeepCopy() *HibernatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(HibernatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernatePolicyStatus) DeepCopyInto(out *HibernatePolicyStatus) {
	*out = *in
	if in.HibernatedWorkloads != nil {
		in, out := &in.HibernatedWorkloads, &out.HibernatedWorkloads
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernatePolicyStatus.
func (in *HibernatePolicyStatus) DeepCopy() *HibernatePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(HibernatePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricePoint) DeepCopyInto(out *PricePoint) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricePoint.
func (in *PricePoint) DeepCopy() *PricePoint {
	if in == nil {
		return nil
	}
	out := new(PricePoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	if in.CustomProviderConfig != nil {
		in, out := &in.CustomProviderConfig, &out.CustomProviderConfig
		*out = new(CustomProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EntsoeConfig != nil {
		in, out := &in.EntsoeConfig, &out.EntsoeConfig
		*out = new(EntsoeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EneverConfig != nil {
		in, out := &in.EneverConfig, &out.EneverConfig
		*out = new(EneverConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfig.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}
